In [1]:
%config IPCompleter.greedy=True
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing as prepro
from sklearn.compose import ColumnTransformer as ctf
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression as linreg
import statsmodels.api as sm
import statsmodels.tools.tools as tool

In [2]:
#importing dataset and deferenciating them
dataset = pd.read_csv('50_Startups.csv')
x =dataset.iloc[:, : -1].values
y =dataset.iloc[:, -1].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [3]:
#emcoding categorical data and transforming data with columntransformer
encode_cat = prepro.LabelEncoder()
x[:,3]= encode_cat.fit_transform(x[:,3])
transformer = ctf([('cities', prepro.OneHotEncoder(),[3])], remainder='passthrough')
x = np.array(transformer.fit_transform(x),dtype = int)
#transformer.fit_transform(x)
#avoiding the dummy variable trap
x = x[:,1:]


c:\users\allaye\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [4]:
#spliting dataset into traning set and test set

x_train, x_test , y_train, y_test = tts(x, y, test_size =0.2, random_state = 0 )

#fitting the dataset with the linear regressor model
regressor = linreg()
regressor.fit(x_train, y_train)

#predicting the results
y_pred = regressor.predict(x_test)


In [5]:
y_pred =y_pred.astype(dtype = int)
y_pred

array([103015, 132581, 132448,  71975, 178537, 116161,  67851,  98791,
       113969, 167921])

In [6]:
y_test = y_test.astype(dtype = int)
y_test

array([103282, 144259, 146121,  77798, 191050, 105008,  81229,  97483,
       110352, 166187])

In [7]:
#implementing Backward elemination
x_const = np.ones((50,1), dtype = int)
x=sm.add_constant( np.append(np.ones((50,1), dtype = int), values = x, axis = 1), prepend='true')
x_opt = x[:,(0,1,2,3,4,5)]
regressor_OLS = sm.OLS(y,x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 05 Jan 2020   Prob (F-statistic):           1.34e-27
Time:                        16:46:24   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.855      7.281      0.000    3.63e+04     6.4e+04
x1           198.7542   3371.026      0.059      0.953   -6595.103    6992.611
x2           -42.0063   3256.058     -0.013      0.990   -6604.161    6520.148
x3             0.8060      0.046     17.368      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.783   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.267
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:
#eleminating the (x2) dataset with highest p-value greater than p-value ==0.05
x_opt = x[:,(0,1,3,4,5)]
regressor_OLS = sm.OLS(y,x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sun, 05 Jan 2020   Prob (F-statistic):           8.49e-29
Time:                        16:49:01   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.901      7.537      0.000    3.67e+04    6.35e+04
x1           220.1847   2900.553      0.076      0.940   -5621.828    6062.197
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.759   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.173
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""